apiVersion: v1
kind: Secret
metadata:
  name: reshare-db-connect
  namespace: minitex-training
type: Opaque
stringData:
  DB_DATABASE: "reshare"
  DB_HOST: "resharedb-postgresql"
  DB_MAXPOOLSIZE: "20"
  DB_USERNAME: "reshare"
  DB_USER: "reshare"
  DB_PASSWORD: "reshare123"
  DB_PORT: "5432"
  # this is used by the directory app
  DATABASE_URL: "postgresql://reshare:reshare123@resharedb-postgresql:5432/reshare"
  DB_TYPE: "postgres"
