# -*- mode: yaml; -*-
apiVersion: v1
kind: Service
metadata:
  name: "mod-settings-1-1-0"
  namespace: "minitex-training"
spec:
  type: "ClusterIP"
  selector:
    app: "mod-settings-1-1-0"
  ports:
    - port: 8081
      name: 8081tcp
