server {
    listen 80;
    server_name rs1-minitex.reshare-dev.indexdata.com;

    root /usr/share/nginx/html/rs1;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 403 404 =200 /index.html;
}

server {
    listen 80;
    server_name rs2-minitex.reshare-dev.indexdata.com;

    root /usr/share/nginx/html/rs2;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 403 404 =200 /index.html;
}

server {
    listen 80;
    server_name rs3-minitex.reshare-dev.indexdata.com;

    root /usr/share/nginx/html/rs3;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 403 404 =200 /index.html;
}
